name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Your buildprod script step would go here
      - name: Build Production
        run: ./scripts/buildprod.sh

      # Setup gcloud CLI
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      # Build and push image
      - name: Build and Push to Artifact Registry
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-437904/notely-ar-repo/notely:release .
